In [1]:
import pandas as pd

In [47]:
df=pd.read_csv('record.csv')
df

,jadwal_konsumsi,jam_konsumsi,nama,nama_obat,telat,__key__,__error__,__has_error__
0,2022-06-25T02:00:00Z,2022-06-26T08:03:20.077Z,IbuC,Metformin,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
1,2022-06-25T05:00:00Z,2022-06-26T08:03:20.740Z,IbuC,Metformin,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
2,2022-06-25T08:00:00Z,2022-06-26T08:03:21.245Z,IbuC,Metformin,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
3,2022-06-26T02:00:00Z,2022-06-26T08:03:21.729Z,IbuC,Metformin,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
4,2022-06-26T05:00:00Z,2022-06-26T08:03:22.179Z,IbuC,Metformin,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
...,...,...,...,...,...,...,...,...
154,2022-08-18T11:00:00Z,2022-08-18T12:16:16.657Z,SETYONO YOHANES,Fenofibrat 300 mg,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
155,2022-07-20T11:00:00Z,2022-07-20T12:09:14.212Z,SETYONO YOHANES,Fenofibrat 300 mg,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
156,2022-08-27T11:00:00Z,2022-08-27T12:12:54.698Z,SETYONO YOHANES,Fenofibrat 300 mg,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
157,2022-08-15T11:00:00Z,2022-08-15T12:05:30.726Z,SETYONO YOHANES,Fenofibrat 300 mg,True,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False
158,2022-07-17T23:00:00Z,2022-07-17T23:49:29.569Z,Yulia Betty Murias,Amlodipin 5,False,"{\n ""__key__"": {\n ""namespace"": """",\n ""...",[],False

In [48]:
df=df[['jadwal_konsumsi','jam_konsumsi','nama','nama_obat','telat']]
df

,jadwal_konsumsi,jam_konsumsi,nama,nama_obat,telat
0,2022-06-25T02:00:00Z,2022-06-26T08:03:20.077Z,IbuC,Metformin,True
1,2022-06-25T05:00:00Z,2022-06-26T08:03:20.740Z,IbuC,Metformin,True
2,2022-06-25T08:00:00Z,2022-06-26T08:03:21.245Z,IbuC,Metformin,True
3,2022-06-26T02:00:00Z,2022-06-26T08:03:21.729Z,IbuC,Metformin,True
4,2022-06-26T05:00:00Z,2022-06-26T08:03:22.179Z,IbuC,Metformin,True
...,...,...,...,...,...
154,2022-08-18T11:00:00Z,2022-08-18T12:16:16.657Z,SETYONO YOHANES,Fenofibrat 300 mg,True
155,2022-07-20T11:00:00Z,2022-07-20T12:09:14.212Z,SETYONO YOHANES,Fenofibrat 300 mg,True
156,2022-08-27T11:00:00Z,2022-08-27T12:12:54.698Z,SETYONO YOHANES,Fenofibrat 300 mg,True
157,2022-08-15T11:00:00Z,2022-08-15T12:05:30.726Z,SETYONO YOHANES,Fenofibrat 300 mg,True
158,2022-07-17T23:00:00Z,2022-07-17T23:49:29.569Z,Yulia Betty Murias,Amlodipin 5,False

In [49]:
df.to_excel('record.xlsx')

In [5]:
df=pd.read_excel('record.xlsx')
del df['Unnamed: 0']
df

,jadwal_konsumsi,jam_konsumsi,nama,nama_obat,telat
0,2022-08-15T05:00:00Z,2022-08-15T06:33:32.264Z,ETTY ASTUTI,Ryzodeg,True
1,2022-08-16T05:00:00Z,2022-08-16T06:43:46.057Z,ETTY ASTUTI,Ryzodeg,True
2,2022-08-20T05:00:00Z,2022-08-20T06:40:55.828Z,ETTY ASTUTI,Ryzodeg,True
3,2022-08-15T05:00:00Z,2022-08-15T06:33:33.421Z,ETTY ASTUTI,Metformin 500 mg (3 x 1),True
4,2022-08-16T05:00:00Z,2022-08-16T06:43:47.247Z,ETTY ASTUTI,Metformin 500 mg (3 x 1),True
...,...,...,...,...,...
125,2022-08-18T11:00:00Z,2022-08-18T12:16:16.657Z,SETYONO YOHANES,Fenofibrat 300 mg,True
126,2022-07-20T11:00:00Z,2022-07-20T12:09:14.212Z,SETYONO YOHANES,Fenofibrat 300 mg,True
127,2022-08-27T11:00:00Z,2022-08-27T12:12:54.698Z,SETYONO YOHANES,Fenofibrat 300 mg,True
128,2022-08-15T11:00:00Z,2022-08-15T12:05:30.726Z,SETYONO YOHANES,Fenofibrat 300 mg,True
129,2022-07-17T23:00:00Z,2022-07-17T23:49:29.569Z,Yulia Betty Murias,Amlodipin 5,False